# site settings
title: Artic
subtitle: Network
email: 
description: Real-time molecular epidemiology for outbreak response
url: "https://artic-network.github.io/website" # the base hostname & protocol for your site # https://artic.network/
author: 
street_address: 
city: 
state: 
zip_code: 
country: 
phone:

# social settings
500px_url:
facebook_url:
github_url: https://github.com/artic-network
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 5

# build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
include:
  [
    "_activities",
    "_news",
    "_protocols",
    "_people",
    "_resources",
    "_resources/ebov",
    "_resources/ncov",
    "_resources/mpxv",
    "_software",
  ]
collections:
  - activities
  - news
  - protocols
  - people
  - resources
  - software
